Enchere/Enchere/Enchere/Enchere/Enchere/Models/ViewModel/EnchereViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Enchere.Models {
    public class EnchereViewModel {
        [Required]
        public string Id { get; set; }
        [Required]
        public string Nom { get; set; }
        [Required]
        public string Description { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Date Inscrit")]
        public DateTime DateInscri { get; set; }
        [Required]
        [Display(Name = "Categorie")]
        public string IdCategorie { get; set; }
        public string Photo { get; set; }
        public string Piece { get; set; }
        public string IdMembre { get; set; }
        public bool Nouveau { get; set; }
        [Display(Name = "En Vente")]
        public bool EnVent { get; set; }
        [Required]
        [Display(Name = "Prix Depart ($)")]
        public decimal PrixDepart { get; set; }
        [Display(Name = "Prix Actuel ($)")]
        public decimal PrixActuel { get; set; }
        public string IdEnchere { get; set; }
        public int Etat { get; set; }

        public EnchereViewModel() { }

        public EnchereViewModel(string id, string nom, string description, DateTime dateInscri, string idCategorie, string photo, string piece, string idMembre, bool nouveau, bool enVent, decimal prixDepart, decimal prixActuel, string idEnchere, int etat) {
            Id = id;
            Nom = nom;
            Description = description;
            DateInscri = dateInscri;
            IdCategorie = idCategorie;
            Photo = photo;
            Piece = piece;
            IdMembre = idMembre;
            Nouveau = nouveau;
            EnVent = enVent;
            PrixDepart = prixDepart;
            PrixActuel = prixActuel;
            IdEnchere = idEnchere;
            Etat = etat;
        }
    }
}

Enchere/Enchere/Enchere/Enchere/Enchere/Controllers/EnchereController.cs
using Enchere.Models;
using Enchere.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using Enchere.Models.ViewModel;
using System.Threading;
using System.Globalization;
using Enchere.Controllers;

namespace Enchere.Dal
{
    public class EnchereController : Controller
    {
      
        [HttpGet]
        public ActionResult MettreEnVente(string idObjet, string idVendeur, bool vente) {
            Encher en = new Encher("0", idObjet, idVendeur, idVendeur, 0, 0, DateTime.Now, DateTime.Now, 0);
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            return View(en);
        }



        [HttpPost]
        public ActionResult MettreEnVente(Encher encher) {
            if (ModelState.IsValid) {
                encher.Id = Utility.IdGenerator.getEncherenId();
                encher.Etat = -1;
                EnchereRequette.insertEncher(encher);

                string formatString = "yyyyMMddHHmmss";
                string sample1 = "20180524121900";
                string sample2 = "20180917102230";
                DateTime dt1 = DateTime.ParseExact(sample1, formatString, null);
                DateTime dt2 = DateTime.ParseExact(sample2, formatString, null);

                StartScheduler sch1 = new StartScheduler();
                ObjetRequette.setObjetEnVente(encher.IdObjet, 1);
                //Encher en = EnchereRequette.getEnchereById(encher.Id);
                //en.Etat = 0;
                //EnchereRequette.updateEnchere(en);
                //sch1.Start(encher.DateDepart, encher.IdObjet, encher.Id);
                sch1.Start(dt1, encher.IdObjet, encher.Id);

                FinishScheduler sch2 = new FinishScheduler();
                //sch2.Start(encher.DateFin, encher.IdObjet, encher.Id);
                sch2.Start(dt2, encher.IdObjet, encher.Id);

                return RedirectToAction("gestionObjetMembre", "Objet");
            }
            return View(encher);
        }

        [HttpGet]
        public ActionResult getEnchereAcheteur(int etat) {
            //   LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            if (ModelState.IsValid) {
                string currentUser = @User.Identity.Name;
                Membre mb = MembreRequette.GetUserByEmail(currentUser);
                List<Encher> list = EnchereRequette.getEncheresAcheteur(mb.Numero, etat);
                List<EnchereViewModel> listObj = new List<EnchereViewModel>();
                foreach (Encher en in list) {
                    Objet obj = ObjetRequette.getObjetById(en.IdObjet);
                    EnchereViewModel model = new EnchereViewModel(obj.Id, obj.Nom, obj.Description, obj.DateInscri, obj.IdCategorie, obj.Photo, obj.Piece, obj.IdMembre, obj.Nouveau, obj.EnVent, obj.PrixDepart, en.PrixAchat, en.Id, en.Etat);
                    listObj.Add(model);
                }

                if (etat == 1) {
                    ViewBag.option = "Les objets achetes:";
                } else if (etat == 0) {
                    ViewBag.option = "Les encheres participes:";
                }
                return View(listObj);
            }
            return View();
        }

        [HttpGet]
        public ActionResult getEnchereVendeur(int etat) {
            //   LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            if (ModelState.IsValid) {
                string currentUser = @User.Identity.Name;
                Membre mb = MembreRequette.GetUserByEmail(currentUser);
                List<Encher> list = EnchereRequette.getEncheresVendeur(mb.Numero, etat);
                List<EnchereViewModel> listObj = new List<EnchereViewModel>();
                foreach (Encher en in list) {
                    Objet obj = ObjetRequette.getObjetById(en.IdObjet);
                    EnchereViewModel model = new EnchereViewModel(obj.Id, obj.Nom, obj.Description, obj.DateInscri, obj.IdCategorie, obj.Photo, obj.Piece, obj.IdMembre, obj.Nouveau, obj.EnVent, obj.PrixDepart, en.PrixAchat, en.Id, en.Etat);
                    listObj.Add(model);
                }
                if (etat == 0) {
                    ViewBag.option = "Les encheres en cours:";
                } else if (etat == 1) {
                    ViewBag.option = "Les encheres remportes:";
                } else if (etat == 2) {
                    ViewBag.option = "Les encheres perdues:";
                }

                //if ()
                return View(listObj);
            }
            return View();
        }

        public ActionResult ListObjetVenduSouPeu()
        {
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            List<Encher> list = EnchereRequette.getEncheresRapport3();
            List<EnchereViewModel> listObj = new List<EnchereViewModel>();
            foreach (Encher en in list)
            {
                Objet obj = ObjetRequette.getObjetById(en.IdObjet);
                EnchereViewModel model = new EnchereViewModel(obj.Id, obj.Nom, obj.Description, en.DateFin, obj.IdCategorie, obj.Photo, obj.Piece, obj.IdMembre, obj.Nouveau, obj.EnVent, obj.PrixDepart, en.PrixAchat, en.Id, en.Etat);
                listObj.Add(model);
            }

           
            return View(listObj);
        
            
         }


        public ActionResult PrintObjetvendu()
        {
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            var list = new ActionAsPdf("getEnchereVendeur", new { etat = 1});
            return list;
        }

        public ActionResult PrintRapprt3()
        {
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            var list = new ActionAsPdf("ListObjetVenduSouPeu");
            return list;
        }


        [HttpGet]
        public ActionResult UpdateEnchere(string id) {
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            Membre mb = MembreRequette.GetUserByEmail(@User.Identity.Name);
            Encher en = EnchereRequette.getEnchereById(id);
            UpdateEnchereViewModel model = new UpdateEnchereViewModel();
            model.Id = en.Id;
            model.IdObjet = en.IdObjet;
            model.IdAcheteur = mb.Numero;
            model.IdVendeur = en.IdVendeur;
            model.PrixAchat = en.PrixAchat;
            model.PasDePrix = en.PasDePrix;
            model.DateDepart = en.DateDepart;
            model.DateFin = en.DateFin;
            model.Etat = en.Etat;
            return View(model);
        }

        [HttpPost]
        public ActionResult UpdateEnchere(UpdateEnchereViewModel en) {
            if (ModelState.IsValid) {
                Encher model = new Encher();
                Encher enOld = EnchereRequette.getEnchereById(en.Id);
                Objet obj = ObjetRequette.getObjetById(en.IdObjet);

                if ((enOld.PrixAchat + enOld.PasDePrix) > en.Prix) {
                    ViewBag.err = "Au moins augmenter le prix par " + enOld.PasDePrix + "$!";
                    return View(en);
                }

                Historique his = EnchereRequette.getHistorique(en.Id);

                if (his.Prix > en.Prix + en.PasDePrix) {
                    model.PrixAchat = en.Prix + en.PasDePrix;
                    model.IdAcheteur = his.IdMembre;
                    //// Send Email to en.IdAcheteur

                } else if (his.Prix >= en.Prix) {
                    model.PrixAchat = his.Prix;
                    model.IdAcheteur = his.IdMembre;
                    //// Send Email to en.IdAcheteur
                } else {
                    model.PrixAchat = his.Prix + en.PasDePrix;
                    model.IdAcheteur = en.IdAcheteur;
                    //// Send Email to his.IdMembre
                }

                Membre mb = MembreRequette.GetUserByNumero(model.IdAcheteur);
                Utility.Mail.SendEmail(obj.Nom, model.PrixAchat, mb.Adresse);


                model.Id = en.Id;
                model.IdObjet = en.IdObjet;
                //model.IdAcheteur = en.IdAcheteur;
                model.IdVendeur = en.IdVendeur;
                //model.PrixAchat = en.Prix;
                model.PasDePrix = en.PasDePrix;
                model.DateDepart = en.DateDepart;
                model.DateFin = en.DateFin;
                model.Etat = en.Etat;

                EnchereRequette.updateEnchere(model);
                his = new Historique(0, en.IdAcheteur, en.Id, en.Prix, DateTime.Now);
                EnchereRequette.insertHistorique(his);
                ////// send E_mail  to add //////
                return RedirectToAction("Index", "Home");

            }
            return View(en);
        }

        public string getLangue()
        {
            string str = "fr";
            str = Request.ServerVariables["HTTP_ACCEPT_LANGUAGE"];
            string cookie = "";
            if (this.ControllerContext.HttpContext.Request.Cookies.AllKeys.Contains("Cookie"))
            {
                cookie = this.ControllerContext.HttpContext.Request.Cookies["Cookie"].Value;
                return cookie;

            }
            else
                return str;
        }

        public static void CreateCulture(string str)
        {
            if (str.IndexOf("fr") != -1)
            {
                Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("fr");

            }
            else if (str.IndexOf("en") != -1)
            {
                Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("en");

            }
        }

    }
}

Enchere/Enchere/Enchere/Enchere/Enchere/Controllers/EvaluationController.cs
using Enchere.Dal;
using Enchere.Models;
using Enchere.Models.ViewModel;
using Enchere.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rotativa;
using System.Threading;
using System.Globalization;

namespace Enchere.Controllers
{
    public class EvaluationController : Controller
    {
       
        [HttpGet]
        public ActionResult Create(string idEnchere, string op, string rtnUrl) {
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            Encher en = EnchereRequette.getEnchereById(idEnchere);
            Evaluation ev = null;
            if (op == "acheteur") {
                ev = new Evaluation("acheteur", idEnchere, DateTime.Now, 0, "", en.IdAcheteur, en.IdVendeur);
            } else if(op == "vendeur") {
                ev = new Evaluation("vendeur", idEnchere, DateTime.Now, 0, "", en.IdVendeur, en.IdAcheteur);
            }

            ViewBag.rtn = rtnUrl;
            return View(ev);         
        }

        [HttpPost]
        public ActionResult Create(Evaluation ev) {
            if (ModelState.IsValid) {
                Encher en = EnchereRequette.getEnchereById(ev.IdEnchere);
                int etat = en.Etat;
                string id = "";

                if (ModelState.IsValid) {
                    if (ev.Id == "acheteur") {
                        if (etat == 1) {
                            EnchereRequette.setEnchereEtat(ev.IdEnchere, 3);
                        } else if (etat == 4) {
                            EnchereRequette.setEnchereEtat(ev.IdEnchere, 5);
                        }
                        id = en.IdVendeur;
                    } else if (ev.Id == "vendeur") {
                        if (etat == 1) {
                            EnchereRequette.setEnchereEtat(ev.IdEnchere, 4);
                        } else if (etat == 3) {
                            EnchereRequette.setEnchereEtat(ev.IdEnchere, 5);
                        }
                        id = en.IdAcheteur;
                    }
                    ev.Id = Utility.IdGenerator.getEvaluationId();
                    EvaluationRequette.insertEvaluation(ev);
                    Membre mb = MembreRequette.GetUserByNumero(id);
                    mb.Cote += ev.Cote;
                    MembreRequette.UpdateCote(mb);
                    ////// update cote d'utilisateur  /////////////////
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(ev);
        }

        [HttpGet]
        public ActionResult List(string idEnchere, string op, string rtnUrl) {
            // LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            Encher en = EnchereRequette.getEnchereById(idEnchere);
            Evaluation ev = null;

            if (op == "acheteur") {
                ev = EvaluationRequette.getEvaluation(idEnchere, en.IdAcheteur);
            } else if (op == "vendeur") {
                ev = EvaluationRequette.getEvaluation(idEnchere, en.IdAcheteur);
            }    

            ViewBag.rtn = rtnUrl;
            return View(ev);
        }

        public ActionResult ListeEvaluationsMembres()
        {
            LangueController.CreateCulture(getLangue());
            List<EvaluationMembre> listObj = EvaluationRequette.getEvaluationMembre();
            return View(listObj);
        }

        public ActionResult PrintEvaluaionMembre()
        {
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            var list = new ActionAsPdf("ListeEvaluationsMembres");
            return list;
        }

        public ActionResult SyntheseVenteAnnuel()
        {
            //  LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            List<Commissions> listCommisions = EvaluationRequette.getCommissions();
            List<SyntheseVentes> synthese = EnchereRequette.getSynthese(listCommisions);
            SyntheseVentes v = synthese[synthese.Count - 1];
            ViewBag.TotalVente = v.TotalVente;
            ViewBag.TotalCom = v.TotalCommision;
            return View(synthese);
        }

        public ActionResult PrintSyntheseVenteAnnuel()
        {
            //   LangueController.CreateCulture(getLangue());
            CreateCulture(getLangue());
            var list = new ActionAsPdf("SyntheseVenteAnnuel");
            return list;
        }

        public string getLangue()
        {
            string str = "fr";
            str = Request.ServerVariables["HTTP_ACCEPT_LANGUAGE"];
            string cookie = "";
            if (this.ControllerContext.HttpContext.Request.Cookies.AllKeys.Contains("Cookie"))
            {
                cookie = this.ControllerContext.HttpContext.Request.Cookies["Cookie"].Value;
                return cookie;

            }
            else
                return str;
        }

        public static void CreateCulture(string str)
        {
            if (str.IndexOf("fr") != -1)
            {
                Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("fr");

            }
            else if (str.IndexOf("en") != -1)
            {
                Thread.CurrentThread.CurrentUICulture = CultureInfo.CreateSpecificCulture("en");

            }
        }
    }
}

Enchere/Enchere/Enchere/Enchere/Enchere/Views/Enchere/ListObjetVenduSouPeu.cshtml
@model IEnumerable<Enchere.Models.EnchereViewModel>
@using Enchere.Ressource

@{
    ViewBag.Title = "ListObjetVenduSouPeu";
}

<h2>Liste Objets Vendus Sous Peu</h2>

<p>
    @Html.ActionLink(@ResourceView.Imprimerrapport, "PrintRapprt3", "Enchere")
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label(@ResourceView.nom2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.Label(@ResourceView.DateFin)
        </th>
        <th>
            @Html.Label(@ResourceView.Catégorie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Piece)
        </th>
        <th>
            @Html.Label(@ResourceView.IdMembre)
        </th>
        <th>
            @Html.Label(@ResourceView.Nouveau)
        </th>
        <th>
            @Html.Label(@ResourceView.EnVent)
        </th>
        <th>
            @Html.Label(@ResourceView.PrixDepart)
        </th>
        <th>
            @Html.Label(@ResourceView.PrixActuel)
        </th>
        <th>
            @Html.Label(@ResourceView.Enchere)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Etat)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateInscri)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCategorie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Photo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Piece)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdMembre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nouveau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnVent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixDepart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixActuel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEnchere)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Etat)
            </td>

        </tr>
    }

</table>

Enchere/Enchere/Enchere/Enchere/Enchere/Views/Enchere/MettreEnVente.cshtml
@model Enchere.Models.Encher
@using Enchere.Ressource
@{
    ViewBag.Title = "MettreEnVente";
}

@section Scripts {
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.js")"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

<h2>Mettre En Vente</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@ResourceView.Enchere</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.IdObjet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdObjet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.IdVendeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdVendeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.IdAcheteur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdAcheteur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(@ResourceView.PrixActuel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrixAchat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrixAchat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(@ResourceView.Augmentationminimale, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PasDePrix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PasDePrix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(@ResourceView.DateDepart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDepart, new { htmlAttributes = new { @class = "form-control date-picker" } })
                @Html.ValidationMessageFor(model => model.DateDepart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label(@ResourceView.DateFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFin, new { htmlAttributes = new { @class = "form-control date-picker" } })
                @Html.ValidationMessageFor(model => model.DateFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@ResourceView.Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(@ResourceView.Listedesobjets, "gestionObjetMembre", "Objet")
</div>

@section MyOtherJavascript {
    <script type="text/javascript">
        $(function () {
            // This will make every element with the class "date-picker" into a DatePicker element
            // $('.date-picker').datepicker();
        })
    </script>
}

Enchere/Enchere/Enchere/Enchere/Enchere/Views/Enchere/getEnchereAcheteur.cshtml
@model IEnumerable<Enchere.Models.EnchereViewModel>
@using Enchere.Ressource
@{
    ViewBag.Title = "gestionEnchereMembre";
}

<h2>@ViewBag.option</h2>

<p>
</p>
<table class="table">
    <tr>
        <th>
            @ResourceView.nom2
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @ResourceView.Inscription
        </th>
        <th>
            @ResourceView.Catégorie
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Piece)
        </th>
        <th>
            @ResourceView.PrixDepart
        </th>
        <th>
            @ResourceView.PrixActuel
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateInscri)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCategorie)
            </td>
            <td>
                @if (item.Photo != null)
                {
                    <img class="card-img-top float-left" src="~/images/@Html.DisplayFor(modelItem => item.Photo)" alt="Card image cap" width=50 height=30>
                }
                else
                {
                    <p>Non</p>
                }
            </td>
            <td>
                @if (item.Piece != null)
                {
                    <a href="@Url.Content("~/pieces/" + @Html.DisplayFor(modelItem => item.Piece))" title=@ResourceView.Telechager>@Html.DisplayFor(modelItem => item.Piece)</a>
                }
                else
                {
                    <p>Non</p>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixDepart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixActuel)
            </td>
            <td>
                @if (item.Etat == 1 || item.Etat == 4)
                {
                    @Html.ActionLink(@ResourceView.Nouvellevaluation, "Create", "Evaluation", new { idEnchere = item.IdEnchere, op = "acheteur", rtnUrl = HttpContext.Current.Request.RawUrl }, null)
                }
                else if (item.Etat == 3 || item.Etat == 5)
                {
                    @Html.ActionLink(@ResourceView.VoirEvaluation, "List", "Evaluation", new { idEnchere = item.IdEnchere, op = "acheteur", rtnUrl = HttpContext.Current.Request.RawUrl }, null)
                }
            </td>
        </tr>
    }

</table>

Enchere/Enchere/Enchere/Enchere/Enchere/Views/Enchere/getEnchereVendeur.cshtml
@model IEnumerable<Enchere.Models.EnchereViewModel>
@using Enchere.Ressource
@{
    ViewBag.Title = "gestionEnchereMembre";
}
@Html.ActionLink("Imprimer rapport", "PrintObjetvendu", "Enchere")
<h2>@ViewBag.option</h2>
<p>
</p>
<table class="table">
    <tr>
        <th>
            @ResourceView.nom2
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @ResourceView.Inscription
        </th>
        <th>
            @ResourceView.Catégorie
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Piece)
        </th>
        <th>
            @ResourceView.PrixDepart
        </th>
        <th>
            @ResourceView.PrixActuel
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateInscri)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCategorie)
            </td>
            <td>
                @if (item.Photo != null)
                {
                    <img class="card-img-top float-left" src="~/images/@Html.DisplayFor(modelItem => item.Photo)" alt="Card image cap" width=50 height=30>
                }
                else
                {
                    <p>Non</p>
                }
            </td>
            <td>
                @if (item.Piece != null)
                {
                    <a href="@Url.Content("~/pieces/" + @Html.DisplayFor(modelItem => item.Piece))" title="telecharger la piece jointe">@Html.DisplayFor(modelItem => item.Piece)</a>
                }
                else
                {
                    <p>Non</p>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixDepart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrixActuel)
            </td>
            <td>
                @if (item.Etat == 1 || item.Etat == 3)
                {
                    @Html.ActionLink(@ResourceView.Nouvellevaluation, "Create", "Evaluation", new { idEnchere = item.IdEnchere, op = "vendeur", rtnUrl = HttpContext.Current.Request.RawUrl }, null)
                }
                else if (item.Etat == 4 || item.Etat == 5)
                {
                    @Html.ActionLink(@ResourceView.VoirEvaluation, "List", "Evaluation", new { idEnchere = item.IdEnchere, op = "vendeur", rtnUrl = HttpContext.Current.Request.RawUrl }, null)
                }
            </td>
        </tr>
    }
</table>